---
- name: Deploy Pointstreak-Groupme to GCP
  # hosts: all   # commented out for safety
  hosts: local
  vars:
    env_name: dev
  vars_files:
    - vars/common.yaml
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:

    - name: Check that target env is defined
      ansible.builtin.assert:
        that:
          - env_name != ""

    - name: Load env-specific vars
      ansible.builtin.include_vars:
        dir: vars
        name: "{{env_name}}.yaml"

    - name: Create base projectDirectory
      ansible.builtin.file:
        path: "{{ install_dir }}/{{ env_name }}/{{ project_dir }}"
        state: directory

    # TODO(gfrasca): Put these inside the src_dir for a flatter structure.
    # Currently strucutred this way for compatibility with deployed projects
    - name: Create "{{ item }}" Directory
      ansible.builtin.file:
        path: "{{ install_dir }}/{{ env_name }}/{{ project_dir }}/{{ item }}"
        state: directory
      loop:
        - logs
        - scripts
        - "{{ src_dir }}"

    - name: Deploy Pointstreak-Groupme to Server
      ansible.builtin.git:
        repo: https://github.com/gmfrasca/pointstreak-groupme.git
        dest: "{{ install_dir }}/{{ env_name }}/{{ project_dir }}/{{ src_dir }}"
        single_branch: true
        version: master

    - name: Check if virtualenv already installed
      ansible.builtin.command: "pipenv --venv"
      args:
        chdir: "{{ install_dir }}/{{ env_name }}/{{ project_dir }}/{{ src_dir }}"
      register: pipenv_venv_check_cmd
      failed_when: false
      ignore_errors: true
      changed_when: false

    - name: Run a pipenv install
      ansible.builtin.command: "pipenv --bare install"
      args:
        chdir: "{{ install_dir }}/{{ env_name }}/{{ project_dir }}/{{ src_dir }}"
      register: pipenv_install_cmd
      when:
        - ('No virtualenv' in pipenv_venv_check_cmd.stderr)

    - name: Copy run script to project directory
      ansible.builtin.copy:
        src: files/psgroupme.sh
        dest: "{{ install_dir }}/{{ env_name }}/{{ project_dir }}/scripts/psgroupme.sh"

    - name: Copy service file to systemd directory
      ansible.builtin.copy:
        src: files/psgroupme.service
        dest: "/etc/systemd/system/psgroupme-{{ env_name }}.service"
      when: run_service

    - name: Start psgroupme service
      ansible.builtin.systemd:
        name: "psgroupme-{{ env_name }}"
        state: started
      when: run_service

    - name: Update crontab to pull codebase once per hour for dev or staging environment
      ansible.builtin.cron:
        name: "Pull codebase once per hour for dev or staging environment"
        minute: "0"
        hour: "*"
        job: "git -C {{ install_dir }}/{{ env_name }}/{{ project_dir }}/{{ src_dir }} pull &> {{ install_dir }}/{{ env_name }}/{{ project_dir }}/logs/gitpull.log"
        user: "{{ user }}"
      when:
        - env_name in ['dev', 'staging']
        - run_service

    - name: Update crontab to restart psgroupme service once per day
      ansible.builtin.cron:
        name: "Restart psgroupme service once per day"
        minute: "15"
        hour: "10"
        job: "sudo systemctl restart psgroupme-{{ env_name }} > {{ install_dir }}/{{ env_name }}/{{ project_dir }}/logs/service.log 2>&1"
        user: "{{ user }}"
      when: run_service

    - name: Copy utility scripts to project directory
      ansible.builtin.copy:
        src: files/util
        dest: "{{ install_dir }}/util"

    - name: Copy config files to project directory
      ansible.builtin.copy:
        src: files/config/{{ env_name }}/{{ item }}
        dest: "{{ install_dir }}/{{ env_name }}/{{ project_dir }}/{{ src_dir }}/config/{{item}}"
      loop:
        - bots.local.yaml
        - timed.local.yaml
        - responses.local.yaml
